### ISSUE TITLE
Signing certificate info did not match chain elements

### ISSUE THREAD

**Issue by UrvishPatel92** [damienbod/AzureIoTHubDps#4]
After adding successfully enrollment group in IOT hub while creating device using intermediate1.pfx it is going to me error like singing certificate info did not match. please check all images as below. what is wrong with it ?

![image](https://user-images.githubusercontent.com/22448835/158320306-671b61b9-6389-4679-be72-b3d44152fe28.png)

![image](https://user-images.githubusercontent.com/22448835/158319992-91fb0718-0f37-49a3-af5f-d42ae001fd16.png)
![image](https://user-images.githubusercontent.com/22448835/158320206-327a7f4a-6323-462d-a3bb-d3c54a3cde17.png)

**Comment by UrvishPatel92** [comment]
Also adding the certificate in dps and verified with verify.pfx.

![image](https://user-images.githubusercontent.com/22448835/158326227-301f85c3-be10-4a96-8e21-a2a8e51346a5.png)

**Comment by damienbod** [comment]
Would need to check, I don't see what's happing here  from this issue.

**Comment by damienbod** [comment]
Updated this now and everything should match

**Comment by damienbod** [comment]
Thanks for reporting, this is fixed now
